import Layout from "@/components/Layout"
import Head from "next/head"
import Image from "next/image"
import profilePic from "../public/assets/profilePic.png"

export default function Home() {
  return (
    <>
      <Head>
        <title>KevinF Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen">
        <Layout className="pt-0">
          <div className="flex items-center justify-between w-full">
            <div className="w-1/2">
              <Image
                src={profilePic}
                alt="Kévin Forget"
                className="w-full h-auto"
              />
            </div>
            <div>
              <h1>
                Transformer la Vision en Réalité avec le Code et le Design
              </h1>
              <p>
                En tant que développeur front-end qualifié, je me consacre à
                transformer des idées en applications Web innovantes. Explorez
                mes derniers projets, mettant en valeur mon
                expertise en React.js et en développement web.
              </p>
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
}
