import Head from "next/head"

export default function Home() {
  return (
    <>
      <Head>
        <title>KevinF Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="bg-white text-black">
        Home
      </main>
    </>
  )
}
